version: 2

sources:
  - name: dbo
    database: dbt

    tables:
      - name: Product
        identifier: Product
        tests:
          - unique:
              column_name: ProductKey
          - string_not_empty:
              column_name: ProductKey

      - name: Region
        identifier: Region
        
      - name: Reseller
        identifier: Reseller
        
      - name: SalesPerson
        identifier: Salesperson
        
      - name: SalesPersonRegion
        identifier: SalespersonRegion
        
      - name: sales
        identifier: Sales
        
      - name: Targets
        identifier: Targets

