version: 2

sources:
  - name: dbo
    database: dbt

    tables:
      - name: Product
        description: "This table has basic information about Products."
        identifier: Product
        freshness:
          warn_after: { count: 1, period: day }  
          error_after: { count: 3, period: day }  
        loaded_at_field: UpdatedAtTimestamp2  

        columns:
          - name: ProductKey  # Assuming this is the correct column name
            description: "Primary Key"
            tests:
              - unique
              - not_null

          - name: isActive
            description: "{{ doc('isActive_description') }}"

        tests:
          - dbt_expectations.expect_table_row_count_to_equal_other_table:
              compare_model: ref('Product_deduplicate')

      - name: Region
        description: "This table has information about Sales Territory."
        identifier: Region
        columns:
          - name: SalesTerritoryKey
            description: "Primary Key"
            tests:
              - unique
              - not_null

      - name: Reseller
        description: "This table has information about Resellers."
        identifier: Reseller
        columns:
          - name: ResellerKey
            description: "Primary Key"
            tests:
              - unique
              - not_null

      - name: SalesPerson
        description: "This table has information about Salesperson."
        identifier: Salesperson
        columns:
          - name: EmployeeKey
            description: "Primary Key"
            tests:
              - unique
              - not_null

      - name: SalesPersonRegion
        description: "This table has information about SalesPerson deployed in each region."
        identifier: SalespersonRegion

      - name: sales
        description: "This table has information about Sales."
        identifier: Sales

      - name: Targets
        description: "This table has information about Salesperson Targets."
        identifier: Targets
